// =================== VOCABULARY DATA ===================
// 10 chủ đề IELTS phổ biến, mỗi chủ đề ~30 từ band 6.5-8.0
// Mỗi từ: word, ipa, pos (part of speech), vi (nghĩa), ex (ví dụ), coll (collocations)

const VOCAB_DATA = {

  // ==================== ENVIRONMENT ====================
  'environment': {
    title: 'Environment',
    titleVi: 'Môi trường',
    icon: '🌍',
    color: 'mint',
    words: [
      { w: 'sustainable', ipa: '/səˈsteɪnəbl/', pos: 'adj', vi: 'bền vững', ex: 'We need to find sustainable solutions to climate change.', coll: 'sustainable development, sustainable energy' },
      { w: 'biodiversity', ipa: '/ˌbaɪəʊdaɪˈvɜːsəti/', pos: 'n', vi: 'đa dạng sinh học', ex: 'The Amazon rainforest has incredible biodiversity.', coll: 'loss of biodiversity, protect biodiversity' },
      { w: 'deforestation', ipa: '/ˌdiːˌfɒrɪˈsteɪʃn/', pos: 'n', vi: 'nạn phá rừng', ex: 'Deforestation is a major cause of species extinction.', coll: 'tackle deforestation, mass deforestation' },
      { w: 'emission', ipa: '/iˈmɪʃn/', pos: 'n', vi: 'sự thải/khí thải', ex: 'Carbon emissions must be reduced urgently.', coll: 'greenhouse gas emissions, reduce emissions' },
      { w: 'renewable', ipa: '/rɪˈnjuːəbl/', pos: 'adj', vi: 'có thể tái tạo', ex: 'Solar power is a renewable energy source.', coll: 'renewable energy, renewable resources' },
      { w: 'pollution', ipa: '/pəˈluːʃn/', pos: 'n', vi: 'ô nhiễm', ex: 'Air pollution kills millions of people each year.', coll: 'air/water/noise pollution, combat pollution' },
      { w: 'depletion', ipa: '/dɪˈpliːʃn/', pos: 'n', vi: 'sự cạn kiệt', ex: 'The depletion of natural resources is alarming.', coll: 'resource depletion, ozone depletion' },
      { w: 'conservation', ipa: '/ˌkɒnsəˈveɪʃn/', pos: 'n', vi: 'bảo tồn', ex: 'Wildlife conservation requires global cooperation.', coll: 'conservation efforts, energy conservation' },
      { w: 'ecosystem', ipa: '/ˈiːkəʊsɪstəm/', pos: 'n', vi: 'hệ sinh thái', ex: 'Coral reefs are fragile ecosystems.', coll: 'marine ecosystem, fragile ecosystem' },
      { w: 'habitat', ipa: '/ˈhæbɪtæt/', pos: 'n', vi: 'môi trường sống', ex: 'Many species are losing their natural habitat.', coll: 'natural habitat, habitat loss' },
      { w: 'endangered', ipa: '/ɪnˈdeɪndʒəd/', pos: 'adj', vi: 'có nguy cơ tuyệt chủng', ex: 'Tigers are an endangered species.', coll: 'endangered species, critically endangered' },
      { w: 'contaminate', ipa: '/kənˈtæmɪneɪt/', pos: 'v', vi: 'làm ô nhiễm', ex: 'Chemicals contaminated the river.', coll: 'contaminate the water/soil' },
      { w: 'eco-friendly', ipa: '/ˌiːkəʊ ˈfrendli/', pos: 'adj', vi: 'thân thiện với môi trường', ex: 'Consumers prefer eco-friendly products.', coll: 'eco-friendly packaging/products' },
      { w: 'fossil fuel', ipa: '/ˈfɒsl fjuːəl/', pos: 'n', vi: 'nhiên liệu hóa thạch', ex: 'Burning fossil fuels releases CO2.', coll: 'rely on fossil fuels, fossil fuel industry' },
      { w: 'global warming', ipa: '/ˌɡləʊbl ˈwɔːmɪŋ/', pos: 'n', vi: 'sự nóng lên toàn cầu', ex: 'Global warming threatens coastal cities.', coll: 'combat global warming, accelerate global warming' },
      { w: 'mitigate', ipa: '/ˈmɪtɪɡeɪt/', pos: 'v', vi: 'giảm nhẹ', ex: 'Trees help mitigate the effects of climate change.', coll: 'mitigate risks, mitigate the impact' },
      { w: 'preserve', ipa: '/prɪˈzɜːv/', pos: 'v', vi: 'bảo tồn', ex: 'National parks help preserve wildlife.', coll: 'preserve heritage, preserve nature' },
      { w: 'extinct', ipa: '/ɪkˈstɪŋkt/', pos: 'adj', vi: 'tuyệt chủng', ex: 'Dinosaurs have been extinct for 65 million years.', coll: 'become extinct, on the verge of extinction' },
      { w: 'recycle', ipa: '/ˌriːˈsaɪkl/', pos: 'v', vi: 'tái chế', ex: 'We should recycle paper and plastic.', coll: 'recycle waste, recycling bin' },
      { w: 'carbon footprint', ipa: '/ˈkɑːbən ˈfʊtprɪnt/', pos: 'n', vi: 'lượng khí carbon thải ra', ex: 'Cycling reduces your carbon footprint.', coll: 'reduce carbon footprint, large carbon footprint' },
      { w: 'overfishing', ipa: '/ˌəʊvəˈfɪʃɪŋ/', pos: 'n', vi: 'đánh bắt quá mức', ex: 'Overfishing has depleted ocean populations.', coll: 'tackle overfishing, ban overfishing' },
      { w: 'plastic pollution', ipa: '/ˈplæstɪk pəˈluːʃn/', pos: 'n', vi: 'ô nhiễm nhựa', ex: 'Plastic pollution affects marine life.', coll: 'reduce plastic pollution, ocean plastic pollution' },
      { w: 'sustainable agriculture', ipa: '/səˈsteɪnəbl ˈæɡrɪkʌltʃə/', pos: 'n', vi: 'nông nghiệp bền vững', ex: 'Sustainable agriculture protects the soil.', coll: 'promote sustainable agriculture' },
      { w: 'wildlife', ipa: '/ˈwaɪldlaɪf/', pos: 'n', vi: 'động vật hoang dã', ex: 'Africa is home to incredible wildlife.', coll: 'protect wildlife, wildlife reserve' },
      { w: 'climate change', ipa: '/ˈklaɪmət tʃeɪndʒ/', pos: 'n', vi: 'biến đổi khí hậu', ex: 'Climate change is the greatest challenge of our time.', coll: 'address climate change, climate change deniers' },
      { w: 'environmentally conscious', ipa: '/ɪnˌvaɪrənˈmentəli ˈkɒnʃəs/', pos: 'adj', vi: 'có ý thức về môi trường', ex: 'Young people are increasingly environmentally conscious.', coll: 'environmentally conscious consumers' },
      { w: 'exploit', ipa: '/ɪkˈsplɔɪt/', pos: 'v', vi: 'khai thác', ex: 'Humans exploit natural resources.', coll: 'exploit resources, ruthlessly exploit' },
      { w: 'drought', ipa: '/draʊt/', pos: 'n', vi: 'hạn hán', ex: 'The region has suffered a severe drought.', coll: 'prolonged drought, drought-resistant crops' },
      { w: 'natural disaster', ipa: '/ˈnætʃrəl dɪˈzɑːstə/', pos: 'n', vi: 'thiên tai', ex: 'Climate change increases natural disasters.', coll: 'devastating natural disaster' },
      { w: 'greenhouse effect', ipa: '/ˈɡriːnhaʊs ɪˈfekt/', pos: 'n', vi: 'hiệu ứng nhà kính', ex: 'The greenhouse effect traps heat in the atmosphere.', coll: 'enhanced greenhouse effect' }
    ]
  },

  // ==================== EDUCATION ====================
  'education': {
    title: 'Education',
    titleVi: 'Giáo dục',
    icon: '📚',
    color: 'sky',
    words: [
      { w: 'curriculum', ipa: '/kəˈrɪkjələm/', pos: 'n', vi: 'chương trình giảng dạy', ex: 'The school curriculum includes mathematics and arts.', coll: 'design a curriculum, school curriculum' },
      { w: 'literacy', ipa: '/ˈlɪtərəsi/', pos: 'n', vi: 'sự biết đọc biết viết', ex: 'Adult literacy rates have improved globally.', coll: 'literacy rate, digital literacy' },
      { w: 'tuition', ipa: '/tjuˈɪʃn/', pos: 'n', vi: 'học phí/dạy kèm', ex: 'University tuition fees are rising.', coll: 'tuition fees, private tuition' },
      { w: 'scholarship', ipa: '/ˈskɒləʃɪp/', pos: 'n', vi: 'học bổng', ex: 'She won a scholarship to study abroad.', coll: 'apply for a scholarship, full scholarship' },
      { w: 'undergraduate', ipa: '/ˌʌndəˈɡrædʒuət/', pos: 'n', vi: 'sinh viên đại học', ex: 'Most undergraduates live on campus.', coll: 'undergraduate degree, undergraduate student' },
      { w: 'postgraduate', ipa: '/ˌpəʊstˈɡrædʒuət/', pos: 'n', vi: 'sau đại học', ex: 'He is doing a postgraduate course in economics.', coll: 'postgraduate study, postgraduate research' },
      { w: 'discipline', ipa: '/ˈdɪsəplɪn/', pos: 'n', vi: 'kỷ luật/lĩnh vực', ex: 'Self-discipline is essential for academic success.', coll: 'strict discipline, academic discipline' },
      { w: 'extracurricular', ipa: '/ˌekstrəkəˈrɪkjələ/', pos: 'adj', vi: 'ngoại khóa', ex: 'Extracurricular activities develop social skills.', coll: 'extracurricular activities' },
      { w: 'rote learning', ipa: '/ˈrəʊt ˈlɜːnɪŋ/', pos: 'n', vi: 'học vẹt', ex: 'Rote learning discourages critical thinking.', coll: 'rely on rote learning' },
      { w: 'critical thinking', ipa: '/ˈkrɪtɪkl ˈθɪŋkɪŋ/', pos: 'n', vi: 'tư duy phản biện', ex: 'Schools should foster critical thinking.', coll: 'develop critical thinking skills' },
      { w: 'mandatory', ipa: '/ˈmændətəri/', pos: 'adj', vi: 'bắt buộc', ex: 'Education is mandatory until age 16.', coll: 'mandatory subject, mandatory attendance' },
      { w: 'enrol', ipa: '/ɪnˈrəʊl/', pos: 'v', vi: 'đăng ký nhập học', ex: 'She enrolled in a language course.', coll: 'enrol in a course, enrol at a university' },
      { w: 'pedagogy', ipa: '/ˈpedəɡɒdʒi/', pos: 'n', vi: 'phương pháp sư phạm', ex: 'Modern pedagogy emphasizes student engagement.', coll: 'innovative pedagogy' },
      { w: 'lifelong learning', ipa: '/ˌlaɪflɒŋ ˈlɜːnɪŋ/', pos: 'n', vi: 'học tập suốt đời', ex: 'Lifelong learning is essential in today\'s economy.', coll: 'promote lifelong learning' },
      { w: 'vocational', ipa: '/vəʊˈkeɪʃənl/', pos: 'adj', vi: 'thuộc về nghề nghiệp', ex: 'Vocational training prepares students for specific careers.', coll: 'vocational training/education/school' },
      { w: 'academic', ipa: '/ˌækəˈdemɪk/', pos: 'adj', vi: 'học thuật', ex: 'Her academic achievements are impressive.', coll: 'academic performance, academic year' },
      { w: 'curriculum overload', ipa: '/kəˈrɪkjələm ˈəʊvələʊd/', pos: 'n', vi: 'chương trình quá tải', ex: 'Curriculum overload stresses students.', coll: 'suffer from curriculum overload' },
      { w: 'plagiarism', ipa: '/ˈpleɪdʒərɪzəm/', pos: 'n', vi: 'đạo văn', ex: 'Universities have strict policies on plagiarism.', coll: 'accuse of plagiarism, detect plagiarism' },
      { w: 'comprehensive', ipa: '/ˌkɒmprɪˈhensɪv/', pos: 'adj', vi: 'toàn diện', ex: 'The course provides comprehensive coverage.', coll: 'comprehensive understanding/review' },
      { w: 'attain', ipa: '/əˈteɪn/', pos: 'v', vi: 'đạt được', ex: 'Students attain different levels of proficiency.', coll: 'attain a qualification, attain a goal' },
      { w: 'gifted', ipa: '/ˈɡɪftɪd/', pos: 'adj', vi: 'có năng khiếu', ex: 'Gifted students need challenging programs.', coll: 'gifted children, academically gifted' },
      { w: 'campus', ipa: '/ˈkæmpəs/', pos: 'n', vi: 'khuôn viên trường', ex: 'The university has a beautiful campus.', coll: 'on campus, campus life' },
      { w: 'illiterate', ipa: '/ɪˈlɪtərət/', pos: 'adj', vi: 'mù chữ', ex: 'Millions of adults remain illiterate.', coll: 'functionally illiterate' },
      { w: 'tutor', ipa: '/ˈtjuːtə/', pos: 'n/v', vi: 'gia sư/dạy kèm', ex: 'Her tutor helped her improve her grades.', coll: 'private tutor, hire a tutor' },
      { w: 'dissertation', ipa: '/ˌdɪsəˈteɪʃn/', pos: 'n', vi: 'luận văn', ex: 'She is writing her doctoral dissertation.', coll: 'submit a dissertation, write a dissertation' },
      { w: 'collaborative', ipa: '/kəˈlæbərətɪv/', pos: 'adj', vi: 'hợp tác', ex: 'Collaborative learning improves teamwork.', coll: 'collaborative learning/project' },
      { w: 'tertiary education', ipa: '/ˈtɜːʃəri ˌedʒuˈkeɪʃn/', pos: 'n', vi: 'giáo dục bậc cao', ex: 'Tertiary education is becoming more accessible.', coll: 'access to tertiary education' },
      { w: 'inclusive', ipa: '/ɪnˈkluːsɪv/', pos: 'adj', vi: 'bao gồm tất cả', ex: 'We need inclusive education for all children.', coll: 'inclusive education/society' },
      { w: 'autonomy', ipa: '/ɔːˈtɒnəmi/', pos: 'n', vi: 'sự tự chủ', ex: 'Learner autonomy is encouraged in modern classrooms.', coll: 'student autonomy, grant autonomy' },
      { w: 'numeracy', ipa: '/ˈnjuːmərəsi/', pos: 'n', vi: 'khả năng tính toán', ex: 'Basic numeracy is essential in daily life.', coll: 'numeracy skills, basic numeracy' }
    ]
  },

  // ==================== TECHNOLOGY ====================
  'technology': {
    title: 'Technology',
    titleVi: 'Công nghệ',
    icon: '💻',
    color: 'lavender',
    words: [
      { w: 'innovation', ipa: '/ˌɪnəˈveɪʃn/', pos: 'n', vi: 'sự đổi mới', ex: 'Innovation drives economic growth.', coll: 'technological innovation, foster innovation' },
      { w: 'artificial intelligence', ipa: '/ˌɑːtɪfɪʃl ɪnˈtelɪdʒəns/', pos: 'n', vi: 'trí tuệ nhân tạo', ex: 'AI is transforming many industries.', coll: 'advances in AI, AI-powered' },
      { w: 'cutting-edge', ipa: '/ˈkʌtɪŋ edʒ/', pos: 'adj', vi: 'tiên tiến nhất', ex: 'They use cutting-edge technology.', coll: 'cutting-edge technology/research' },
      { w: 'automation', ipa: '/ˌɔːtəˈmeɪʃn/', pos: 'n', vi: 'sự tự động hóa', ex: 'Automation may replace many jobs.', coll: 'industrial automation, fear of automation' },
      { w: 'cybersecurity', ipa: '/ˌsaɪbəsɪˈkjʊərəti/', pos: 'n', vi: 'an ninh mạng', ex: 'Cybersecurity is a growing concern.', coll: 'cybersecurity threats, cybersecurity expert' },
      { w: 'breakthrough', ipa: '/ˈbreɪkθruː/', pos: 'n', vi: 'đột phá', ex: 'Scientists made a major breakthrough.', coll: 'major breakthrough, scientific breakthrough' },
      { w: 'obsolete', ipa: '/ˈɒbsəliːt/', pos: 'adj', vi: 'lỗi thời', ex: 'Many skills become obsolete quickly.', coll: 'render obsolete, become obsolete' },
      { w: 'digital divide', ipa: '/ˈdɪdʒɪtl dɪˈvaɪd/', pos: 'n', vi: 'khoảng cách số', ex: 'The digital divide affects rural areas.', coll: 'bridge the digital divide' },
      { w: 'gadget', ipa: '/ˈɡædʒɪt/', pos: 'n', vi: 'thiết bị nhỏ', ex: 'He loves the latest gadgets.', coll: 'electronic gadget, modern gadget' },
      { w: 'app', ipa: '/æp/', pos: 'n', vi: 'ứng dụng', ex: 'There\'s an app for almost everything.', coll: 'download an app, mobile app' },
      { w: 'algorithm', ipa: '/ˈælɡərɪðəm/', pos: 'n', vi: 'thuật toán', ex: 'Search engines use complex algorithms.', coll: 'develop an algorithm, search algorithm' },
      { w: 'virtual', ipa: '/ˈvɜːtʃuəl/', pos: 'adj', vi: 'ảo', ex: 'Virtual reality offers immersive experiences.', coll: 'virtual reality, virtual meeting' },
      { w: 'remote', ipa: '/rɪˈməʊt/', pos: 'adj', vi: 'từ xa', ex: 'Remote work has become common.', coll: 'remote learning, work remotely' },
      { w: 'state-of-the-art', ipa: '/ˌsteɪt əv ði ˈɑːt/', pos: 'adj', vi: 'hiện đại nhất', ex: 'The lab has state-of-the-art equipment.', coll: 'state-of-the-art facilities' },
      { w: 'revolutionise', ipa: '/ˌrevəˈluːʃənaɪz/', pos: 'v', vi: 'cách mạng hóa', ex: 'The internet has revolutionised communication.', coll: 'revolutionise the industry' },
      { w: 'data privacy', ipa: '/ˈdeɪtə ˈprɪvəsi/', pos: 'n', vi: 'quyền riêng tư dữ liệu', ex: 'Data privacy is a critical issue.', coll: 'protect data privacy' },
      { w: 'social media', ipa: '/ˈsəʊʃl ˈmiːdiə/', pos: 'n', vi: 'mạng xã hội', ex: 'Social media influences public opinion.', coll: 'social media platform, addicted to social media' },
      { w: 'hack', ipa: '/hæk/', pos: 'v', vi: 'tấn công mạng', ex: 'Hackers can steal personal information.', coll: 'hack into a system, get hacked' },
      { w: 'misinformation', ipa: '/ˌmɪsɪnfəˈmeɪʃn/', pos: 'n', vi: 'thông tin sai lệch', ex: 'Social media spreads misinformation rapidly.', coll: 'spread misinformation, combat misinformation' },
      { w: 'streamline', ipa: '/ˈstriːmlaɪn/', pos: 'v', vi: 'tinh giản', ex: 'Technology can streamline business processes.', coll: 'streamline operations/processes' },
      { w: 'user-friendly', ipa: '/ˌjuːzə ˈfrendli/', pos: 'adj', vi: 'thân thiện với người dùng', ex: 'The interface is very user-friendly.', coll: 'user-friendly design/interface' },
      { w: 'glitch', ipa: '/ɡlɪtʃ/', pos: 'n', vi: 'lỗi nhỏ', ex: 'A software glitch caused the crash.', coll: 'software glitch, minor glitch' },
      { w: 'screen time', ipa: '/ˈskriːn taɪm/', pos: 'n', vi: 'thời gian dùng màn hình', ex: 'Children spend too much screen time.', coll: 'reduce screen time, excessive screen time' },
      { w: 'tech-savvy', ipa: '/ˌtek ˈsævi/', pos: 'adj', vi: 'rành công nghệ', ex: 'Young people tend to be tech-savvy.', coll: 'tech-savvy users/generation' },
      { w: 'e-commerce', ipa: '/ˈiː kɒmɜːs/', pos: 'n', vi: 'thương mại điện tử', ex: 'E-commerce has changed shopping habits.', coll: 'e-commerce platform, boom in e-commerce' },
      { w: 'cloud computing', ipa: '/klaʊd kəmˈpjuːtɪŋ/', pos: 'n', vi: 'điện toán đám mây', ex: 'Cloud computing reduces hardware costs.', coll: 'cloud computing services' },
      { w: 'connectivity', ipa: '/ˌkɒnekˈtɪvəti/', pos: 'n', vi: 'sự kết nối', ex: 'Connectivity is essential for modern business.', coll: 'internet connectivity, global connectivity' },
      { w: 'dependence', ipa: '/dɪˈpendəns/', pos: 'n', vi: 'sự phụ thuộc', ex: 'Our dependence on technology is increasing.', coll: 'dependence on technology' },
      { w: 'paramount', ipa: '/ˈpærəmaʊnt/', pos: 'adj', vi: 'tối quan trọng', ex: 'Privacy is of paramount importance.', coll: 'of paramount importance' },
      { w: 'disruptive', ipa: '/dɪsˈrʌptɪv/', pos: 'adj', vi: 'mang tính đột phá', ex: 'Disruptive technology changes industries.', coll: 'disruptive technology/innovation' }
    ]
  },

  // ==================== HEALTH ====================
  'health': {
    title: 'Health',
    titleVi: 'Sức khỏe',
    icon: '🏥',
    color: 'coral',
    words: [
      { w: 'sedentary', ipa: '/ˈsedntri/', pos: 'adj', vi: 'ít vận động', ex: 'A sedentary lifestyle leads to health problems.', coll: 'sedentary lifestyle, sedentary job' },
      { w: 'obesity', ipa: '/əʊˈbiːsəti/', pos: 'n', vi: 'béo phì', ex: 'Childhood obesity is rising.', coll: 'childhood obesity, tackle obesity' },
      { w: 'nutritious', ipa: '/njuˈtrɪʃəs/', pos: 'adj', vi: 'bổ dưỡng', ex: 'Vegetables are highly nutritious.', coll: 'nutritious meal/diet' },
      { w: 'well-being', ipa: '/ˌwel ˈbiːɪŋ/', pos: 'n', vi: 'sự an lành', ex: 'Mental well-being is as important as physical health.', coll: 'mental well-being, sense of well-being' },
      { w: 'chronic', ipa: '/ˈkrɒnɪk/', pos: 'adj', vi: 'mãn tính', ex: 'Diabetes is a chronic disease.', coll: 'chronic illness/pain/condition' },
      { w: 'immune system', ipa: '/ɪˈmjuːn ˈsɪstəm/', pos: 'n', vi: 'hệ miễn dịch', ex: 'A strong immune system fights infections.', coll: 'boost the immune system' },
      { w: 'pandemic', ipa: '/pænˈdemɪk/', pos: 'n', vi: 'đại dịch', ex: 'COVID-19 became a global pandemic.', coll: 'global pandemic, pandemic outbreak' },
      { w: 'hygiene', ipa: '/ˈhaɪdʒiːn/', pos: 'n', vi: 'vệ sinh', ex: 'Good hygiene prevents disease.', coll: 'personal hygiene, oral hygiene' },
      { w: 'preventative', ipa: '/prɪˈventətɪv/', pos: 'adj', vi: 'phòng ngừa', ex: 'Preventative care saves lives.', coll: 'preventative measures/medicine' },
      { w: 'longevity', ipa: '/lɒnˈdʒevəti/', pos: 'n', vi: 'tuổi thọ cao', ex: 'Exercise contributes to longevity.', coll: 'increased longevity, secret to longevity' },
      { w: 'physician', ipa: '/fɪˈzɪʃn/', pos: 'n', vi: 'bác sĩ', ex: 'Consult a physician for medical advice.', coll: 'family physician, consult a physician' },
      { w: 'symptom', ipa: '/ˈsɪmptəm/', pos: 'n', vi: 'triệu chứng', ex: 'The symptoms include fever and cough.', coll: 'show symptoms, mild symptoms' },
      { w: 'outbreak', ipa: '/ˈaʊtbreɪk/', pos: 'n', vi: 'sự bùng phát', ex: 'There was a flu outbreak last winter.', coll: 'disease outbreak, contain an outbreak' },
      { w: 'epidemic', ipa: '/ˌepɪˈdemɪk/', pos: 'n', vi: 'dịch bệnh', ex: 'The obesity epidemic affects developed nations.', coll: 'epidemic of, fight an epidemic' },
      { w: 'mental health', ipa: '/ˈmentl helθ/', pos: 'n', vi: 'sức khỏe tinh thần', ex: 'Mental health awareness is increasing.', coll: 'mental health issues, mental health crisis' },
      { w: 'sanitation', ipa: '/ˌsænɪˈteɪʃn/', pos: 'n', vi: 'vệ sinh môi trường', ex: 'Poor sanitation causes diseases.', coll: 'access to sanitation, basic sanitation' },
      { w: 'malnutrition', ipa: '/ˌmælnjuːˈtrɪʃn/', pos: 'n', vi: 'suy dinh dưỡng', ex: 'Child malnutrition is a serious issue.', coll: 'severe malnutrition' },
      { w: 'vaccinate', ipa: '/ˈvæksɪneɪt/', pos: 'v', vi: 'tiêm vaccine', ex: 'Children should be vaccinated against measles.', coll: 'vaccinate against, get vaccinated' },
      { w: 'overweight', ipa: '/ˌəʊvəˈweɪt/', pos: 'adj', vi: 'thừa cân', ex: 'Being overweight increases health risks.', coll: 'overweight people, slightly overweight' },
      { w: 'addiction', ipa: '/əˈdɪkʃn/', pos: 'n', vi: 'sự nghiện', ex: 'Drug addiction is a public health issue.', coll: 'drug addiction, struggle with addiction' },
      { w: 'rehabilitation', ipa: '/ˌriːəˌbɪlɪˈteɪʃn/', pos: 'n', vi: 'phục hồi chức năng', ex: 'After the accident, she required rehabilitation.', coll: 'physical rehabilitation, rehab centre' },
      { w: 'lifestyle disease', ipa: '/ˈlaɪfstaɪl dɪˈziːz/', pos: 'n', vi: 'bệnh do lối sống', ex: 'Lifestyle diseases like diabetes are preventable.', coll: 'suffer from lifestyle diseases' },
      { w: 'cardiovascular', ipa: '/ˌkɑːdiəʊˈvæskjələ/', pos: 'adj', vi: 'tim mạch', ex: 'Cardiovascular disease is the leading cause of death.', coll: 'cardiovascular disease/health' },
      { w: 'diagnose', ipa: '/ˈdaɪəɡnəʊz/', pos: 'v', vi: 'chẩn đoán', ex: 'The doctor diagnosed her with the flu.', coll: 'diagnose a disease, be diagnosed with' },
      { w: 'remedy', ipa: '/ˈremədi/', pos: 'n', vi: 'phương thuốc/cách khắc phục', ex: 'Honey is a natural remedy for sore throats.', coll: 'home remedy, natural remedy' },
      { w: 'side effect', ipa: '/ˈsaɪd ɪfekt/', pos: 'n', vi: 'tác dụng phụ', ex: 'This drug has serious side effects.', coll: 'unpleasant side effects, suffer from side effects' },
      { w: 'sedentary lifestyle', ipa: '/ˈsedntri ˈlaɪfstaɪl/', pos: 'n', vi: 'lối sống ít vận động', ex: 'A sedentary lifestyle causes health problems.', coll: 'lead a sedentary lifestyle' },
      { w: 'public health', ipa: '/ˈpʌblɪk helθ/', pos: 'n', vi: 'sức khỏe cộng đồng', ex: 'Smoking is a major public health concern.', coll: 'public health issue/crisis' },
      { w: 'subsidise', ipa: '/ˈsʌbsɪdaɪz/', pos: 'v', vi: 'trợ cấp', ex: 'The government subsidises healthcare.', coll: 'subsidise healthcare/medicine' },
      { w: 'allergy', ipa: '/ˈælədʒi/', pos: 'n', vi: 'dị ứng', ex: 'She has an allergy to peanuts.', coll: 'have an allergy to, food allergy' }
    ]
  },

  // ==================== WORK ====================
  'work': {
    title: 'Work',
    titleVi: 'Công việc',
    icon: '💼',
    color: 'tangerine',
    words: [
      { w: 'workforce', ipa: '/ˈwɜːkfɔːs/', pos: 'n', vi: 'lực lượng lao động', ex: 'The workforce is becoming more diverse.', coll: 'enter the workforce, skilled workforce' },
      { w: 'unemployment', ipa: '/ˌʌnɪmˈplɔɪmənt/', pos: 'n', vi: 'thất nghiệp', ex: 'Unemployment is at an all-time low.', coll: 'high unemployment, youth unemployment' },
      { w: 'productivity', ipa: '/ˌprɒdʌkˈtɪvəti/', pos: 'n', vi: 'năng suất', ex: 'Remote work can boost productivity.', coll: 'increase productivity, productivity levels' },
      { w: 'career path', ipa: '/kəˈrɪə pɑːθ/', pos: 'n', vi: 'lộ trình sự nghiệp', ex: 'She is following a clear career path.', coll: 'choose a career path, follow a career path' },
      { w: 'colleague', ipa: '/ˈkɒliːɡ/', pos: 'n', vi: 'đồng nghiệp', ex: 'My colleagues are very supportive.', coll: 'work with colleagues, fellow colleague' },
      { w: 'promotion', ipa: '/prəˈməʊʃn/', pos: 'n', vi: 'sự thăng chức', ex: 'He got a promotion last month.', coll: 'get/earn a promotion, deserve a promotion' },
      { w: 'work-life balance', ipa: '/ˈwɜːk laɪf ˈbæləns/', pos: 'n', vi: 'cân bằng công việc/cuộc sống', ex: 'Maintaining work-life balance is challenging.', coll: 'achieve work-life balance' },
      { w: 'overtime', ipa: '/ˈəʊvətaɪm/', pos: 'n', vi: 'làm thêm giờ', ex: 'She works a lot of overtime.', coll: 'work overtime, paid overtime' },
      { w: 'redundancy', ipa: '/rɪˈdʌndənsi/', pos: 'n', vi: 'sự dôi dư việc làm', ex: 'Many faced redundancy during the recession.', coll: 'face redundancy, redundancy package' },
      { w: 'self-employed', ipa: '/ˌself ɪmˈplɔɪd/', pos: 'adj', vi: 'làm tự do', ex: 'He has been self-employed for ten years.', coll: 'work as self-employed' },
      { w: 'entrepreneur', ipa: '/ˌɒntrəprəˈnɜː/', pos: 'n', vi: 'doanh nhân', ex: 'Successful entrepreneurs take risks.', coll: 'young entrepreneur, become an entrepreneur' },
      { w: 'commute', ipa: '/kəˈmjuːt/', pos: 'v/n', vi: 'đi làm hàng ngày', ex: 'I commute to work by train.', coll: 'long commute, daily commute' },
      { w: 'incentive', ipa: '/ɪnˈsentɪv/', pos: 'n', vi: 'sự khuyến khích', ex: 'Bonuses are a powerful incentive.', coll: 'financial incentive, provide incentives' },
      { w: 'wage', ipa: '/weɪdʒ/', pos: 'n', vi: 'tiền lương', ex: 'Workers demanded higher wages.', coll: 'minimum wage, low wages' },
      { w: 'recruitment', ipa: '/rɪˈkruːtmənt/', pos: 'n', vi: 'tuyển dụng', ex: 'The recruitment process can take weeks.', coll: 'recruitment agency, recruitment process' },
      { w: 'flexible hours', ipa: '/ˈfleksəbl aʊəz/', pos: 'n', vi: 'giờ làm việc linh hoạt', ex: 'Many companies now offer flexible hours.', coll: 'work flexible hours' },
      { w: 'expertise', ipa: '/ˌekspɜːˈtiːz/', pos: 'n', vi: 'chuyên môn', ex: 'Her expertise is invaluable to the team.', coll: 'technical expertise, share expertise' },
      { w: 'burnout', ipa: '/ˈbɜːnaʊt/', pos: 'n', vi: 'kiệt sức', ex: 'Burnout is common in high-pressure jobs.', coll: 'suffer from burnout, prevent burnout' },
      { w: 'wage gap', ipa: '/ˈweɪdʒ ɡæp/', pos: 'n', vi: 'khoảng cách lương', ex: 'The gender wage gap persists.', coll: 'gender wage gap, narrow the wage gap' },
      { w: 'glass ceiling', ipa: '/ˌɡlɑːs ˈsiːlɪŋ/', pos: 'n', vi: 'rào cản vô hình', ex: 'Women still face a glass ceiling.', coll: 'break the glass ceiling' },
      { w: 'workaholic', ipa: '/ˌwɜːkəˈhɒlɪk/', pos: 'n', vi: 'người nghiện công việc', ex: 'He\'s a workaholic who never takes breaks.', coll: 'self-confessed workaholic' },
      { w: 'redundant', ipa: '/rɪˈdʌndənt/', pos: 'adj', vi: 'dư thừa, bị sa thải', ex: 'Hundreds of workers were made redundant.', coll: 'made redundant' },
      { w: 'monotonous', ipa: '/məˈnɒtənəs/', pos: 'adj', vi: 'đơn điệu', ex: 'Factory work can be monotonous.', coll: 'monotonous work/job/task' },
      { w: 'lucrative', ipa: '/ˈluːkrətɪv/', pos: 'adj', vi: 'sinh lợi', ex: 'Software engineering is a lucrative career.', coll: 'lucrative career/contract' },
      { w: 'stepping stone', ipa: '/ˈstepɪŋ stəʊn/', pos: 'n', vi: 'bàn đạp', ex: 'This job is a stepping stone to better positions.', coll: 'a stepping stone to' },
      { w: 'pay rise', ipa: '/ˈpeɪ raɪz/', pos: 'n', vi: 'tăng lương', ex: 'She got a 10% pay rise.', coll: 'ask for a pay rise, get a pay rise' },
      { w: 'job satisfaction', ipa: '/dʒɒb sætɪsˈfækʃn/', pos: 'n', vi: 'sự hài lòng với công việc', ex: 'Job satisfaction matters more than salary.', coll: 'high job satisfaction' },
      { w: 'gig economy', ipa: '/ˈɡɪɡ ɪˈkɒnəmi/', pos: 'n', vi: 'nền kinh tế tự do', ex: 'The gig economy offers flexibility.', coll: 'rise of the gig economy' },
      { w: 'pension', ipa: '/ˈpenʃn/', pos: 'n', vi: 'lương hưu', ex: 'He receives a generous pension.', coll: 'state pension, pension scheme' },
      { w: 'workplace', ipa: '/ˈwɜːkpleɪs/', pos: 'n', vi: 'nơi làm việc', ex: 'A positive workplace boosts morale.', coll: 'in the workplace, workplace culture' }
    ]
  },

  // ==================== SOCIETY ====================
  'society': {
    title: 'Society',
    titleVi: 'Xã hội',
    icon: '🏛️',
    color: 'hotpink',
    words: [
      { w: 'inequality', ipa: '/ˌɪnɪˈkwɒləti/', pos: 'n', vi: 'bất bình đẳng', ex: 'Income inequality is widening.', coll: 'income inequality, social inequality' },
      { w: 'discrimination', ipa: '/dɪˌskrɪmɪˈneɪʃn/', pos: 'n', vi: 'sự phân biệt đối xử', ex: 'Racial discrimination is illegal.', coll: 'face discrimination, gender discrimination' },
      { w: 'demographic', ipa: '/ˌdeməˈɡræfɪk/', pos: 'adj/n', vi: 'thuộc về nhân khẩu', ex: 'There have been major demographic changes.', coll: 'demographic shift, ageing demographic' },
      { w: 'urbanisation', ipa: '/ˌɜːbənaɪˈzeɪʃn/', pos: 'n', vi: 'đô thị hóa', ex: 'Rapid urbanisation strains infrastructure.', coll: 'rapid urbanisation, pace of urbanisation' },
      { w: 'integration', ipa: '/ˌɪntɪˈɡreɪʃn/', pos: 'n', vi: 'sự hòa nhập', ex: 'Successful integration takes time.', coll: 'social integration, integration policy' },
      { w: 'immigrant', ipa: '/ˈɪmɪɡrənt/', pos: 'n', vi: 'người nhập cư', ex: 'Immigrants contribute to the economy.', coll: 'illegal immigrant, first-generation immigrant' },
      { w: 'cohesion', ipa: '/kəʊˈhiːʒn/', pos: 'n', vi: 'sự gắn kết', ex: 'Social cohesion is vital for stability.', coll: 'social cohesion, lack of cohesion' },
      { w: 'minority', ipa: '/maɪˈnɒrəti/', pos: 'n', vi: 'thiểu số', ex: 'Minority rights must be protected.', coll: 'ethnic minority, minority group' },
      { w: 'poverty', ipa: '/ˈpɒvəti/', pos: 'n', vi: 'nghèo đói', ex: 'Many countries struggle with poverty.', coll: 'extreme poverty, alleviate poverty' },
      { w: 'social welfare', ipa: '/ˈsəʊʃl ˈwelfeə/', pos: 'n', vi: 'phúc lợi xã hội', ex: 'The state provides social welfare.', coll: 'social welfare system, welfare benefits' },
      { w: 'gender equality', ipa: '/ˈdʒendər ɪˈkwɒləti/', pos: 'n', vi: 'bình đẳng giới', ex: 'Gender equality remains a global goal.', coll: 'promote gender equality' },
      { w: 'multicultural', ipa: '/ˌmʌltiˈkʌltʃərəl/', pos: 'adj', vi: 'đa văn hóa', ex: 'London is a multicultural city.', coll: 'multicultural society/community' },
      { w: 'ageing population', ipa: '/ˈeɪdʒɪŋ ˌpɒpjuˈleɪʃn/', pos: 'n', vi: 'dân số già hóa', ex: 'Japan has a rapidly ageing population.', coll: 'rapidly ageing population' },
      { w: 'birth rate', ipa: '/ˈbɜːθ reɪt/', pos: 'n', vi: 'tỷ lệ sinh', ex: 'The birth rate has declined.', coll: 'declining birth rate, falling birth rate' },
      { w: 'gentrification', ipa: '/ˌdʒentrɪfɪˈkeɪʃn/', pos: 'n', vi: 'sự "thượng lưu hóa" khu phố', ex: 'Gentrification displaces poor residents.', coll: 'urban gentrification' },
      { w: 'community', ipa: '/kəˈmjuːnəti/', pos: 'n', vi: 'cộng đồng', ex: 'A strong community supports its members.', coll: 'local community, sense of community' },
      { w: 'tolerance', ipa: '/ˈtɒlərəns/', pos: 'n', vi: 'lòng khoan dung', ex: 'Religious tolerance is essential.', coll: 'religious tolerance, show tolerance' },
      { w: 'prejudice', ipa: '/ˈpredʒudɪs/', pos: 'n', vi: 'định kiến', ex: 'Prejudice prevents social progress.', coll: 'racial prejudice, overcome prejudice' },
      { w: 'stereotype', ipa: '/ˈsteriətaɪp/', pos: 'n', vi: 'định kiến rập khuôn', ex: 'Negative stereotypes harm minorities.', coll: 'cultural stereotype, reinforce a stereotype' },
      { w: 'civic duty', ipa: '/ˈsɪvɪk ˈdjuːti/', pos: 'n', vi: 'nghĩa vụ công dân', ex: 'Voting is a civic duty.', coll: 'fulfill civic duty' },
      { w: 'philanthropy', ipa: '/fɪˈlænθrəpi/', pos: 'n', vi: 'hoạt động từ thiện', ex: 'Bill Gates is famous for his philanthropy.', coll: 'corporate philanthropy' },
      { w: 'volunteer', ipa: '/ˌvɒlənˈtɪə/', pos: 'v/n', vi: 'tình nguyện', ex: 'Many people volunteer at charities.', coll: 'volunteer work, regular volunteer' },
      { w: 'marginalise', ipa: '/ˈmɑːdʒɪnəlaɪz/', pos: 'v', vi: 'gạt ra ngoài lề', ex: 'Some groups are marginalised in society.', coll: 'marginalise minorities' },
      { w: 'norm', ipa: '/nɔːm/', pos: 'n', vi: 'chuẩn mực', ex: 'Social norms vary between cultures.', coll: 'social norms, cultural norms' },
      { w: 'generation gap', ipa: '/ˌdʒenəˈreɪʃn ɡæp/', pos: 'n', vi: 'khoảng cách thế hệ', ex: 'The generation gap can cause family conflicts.', coll: 'bridge the generation gap' },
      { w: 'globalisation', ipa: '/ˌɡləʊbəlaɪˈzeɪʃn/', pos: 'n', vi: 'toàn cầu hóa', ex: 'Globalisation has both benefits and drawbacks.', coll: 'effects of globalisation' },
      { w: 'segregation', ipa: '/ˌseɡrɪˈɡeɪʃn/', pos: 'n', vi: 'sự phân biệt', ex: 'Racial segregation was once legal.', coll: 'racial segregation' },
      { w: 'rights', ipa: '/raɪts/', pos: 'n', vi: 'quyền', ex: 'Human rights must be protected.', coll: 'human rights, civil rights' },
      { w: 'patriarchy', ipa: '/ˈpeɪtriɑːki/', pos: 'n', vi: 'chế độ phụ hệ', ex: 'Feminists challenge patriarchy.', coll: 'dismantle patriarchy' },
      { w: 'class divide', ipa: '/klɑːs dɪˈvaɪd/', pos: 'n', vi: 'khoảng cách giai cấp', ex: 'The class divide is widening.', coll: 'widening class divide' }
    ]
  },

  // ==================== TRAVEL ====================
  'travel': {
    title: 'Travel',
    titleVi: 'Du lịch',
    icon: '✈️',
    color: 'sunshine',
    words: [
      { w: 'destination', ipa: '/ˌdestɪˈneɪʃn/', pos: 'n', vi: 'điểm đến', ex: 'Bali is a popular tourist destination.', coll: 'popular destination, holiday destination' },
      { w: 'itinerary', ipa: '/aɪˈtɪnərəri/', pos: 'n', vi: 'lịch trình', ex: 'We planned a detailed itinerary.', coll: 'plan/follow an itinerary' },
      { w: 'accommodation', ipa: '/əˌkɒməˈdeɪʃn/', pos: 'n', vi: 'chỗ ở', ex: 'We need to book accommodation in advance.', coll: 'find/book accommodation' },
      { w: 'sightseeing', ipa: '/ˈsaɪtsiːɪŋ/', pos: 'n', vi: 'tham quan', ex: 'We spent the morning sightseeing.', coll: 'go sightseeing' },
      { w: 'backpacking', ipa: '/ˈbækpækɪŋ/', pos: 'n', vi: 'du lịch bụi', ex: 'They went backpacking across Europe.', coll: 'go backpacking' },
      { w: 'tourism', ipa: '/ˈtʊərɪzəm/', pos: 'n', vi: 'ngành du lịch', ex: 'Tourism is the country\'s main industry.', coll: 'eco-tourism, mass tourism' },
      { w: 'wanderlust', ipa: '/ˈwɒndəlʌst/', pos: 'n', vi: 'niềm đam mê du lịch', ex: 'She has been bitten by wanderlust.', coll: 'satisfy wanderlust' },
      { w: 'culture shock', ipa: '/ˈkʌltʃə ʃɒk/', pos: 'n', vi: 'sốc văn hóa', ex: 'I experienced culture shock in Tokyo.', coll: 'experience culture shock' },
      { w: 'adventure', ipa: '/ədˈventʃə/', pos: 'n', vi: 'cuộc phiêu lưu', ex: 'Travel is full of adventure.', coll: 'sense of adventure, adventure travel' },
      { w: 'exotic', ipa: '/ɪɡˈzɒtɪk/', pos: 'adj', vi: 'kỳ lạ, độc đáo', ex: 'They visited exotic islands.', coll: 'exotic destination/location' },
      { w: 'jet lag', ipa: '/ˈdʒet læɡ/', pos: 'n', vi: 'mệt mỏi do lệch múi giờ', ex: 'I had severe jet lag after the flight.', coll: 'suffer from jet lag' },
      { w: 'getaway', ipa: '/ˈɡetəweɪ/', pos: 'n', vi: 'kỳ nghỉ ngắn', ex: 'We need a weekend getaway.', coll: 'weekend getaway, romantic getaway' },
      { w: 'authentic', ipa: '/ɔːˈθentɪk/', pos: 'adj', vi: 'chính gốc, đích thực', ex: 'We tried authentic Italian food.', coll: 'authentic experience/cuisine' },
      { w: 'breathtaking', ipa: '/ˈbreθteɪkɪŋ/', pos: 'adj', vi: 'ngoạn mục', ex: 'The views were breathtaking.', coll: 'breathtaking views/scenery' },
      { w: 'overpriced', ipa: '/ˌəʊvəˈpraɪst/', pos: 'adj', vi: 'quá đắt', ex: 'The hotel was overpriced.', coll: 'overpriced restaurant/hotel' },
      { w: 'off the beaten track', ipa: '/ɒf ðə ˈbiːtn træk/', pos: 'phrase', vi: 'ít người biết đến', ex: 'We love places off the beaten track.', coll: 'go off the beaten track' },
      { w: 'expedition', ipa: '/ˌekspəˈdɪʃn/', pos: 'n', vi: 'cuộc thám hiểm', ex: 'They led an expedition to Antarctica.', coll: 'mount an expedition' },
      { w: 'souvenir', ipa: '/ˌsuːvəˈnɪə/', pos: 'n', vi: 'quà lưu niệm', ex: 'She bought souvenirs for her friends.', coll: 'buy souvenirs, tacky souvenir' },
      { w: 'heritage site', ipa: '/ˈherɪtɪdʒ saɪt/', pos: 'n', vi: 'di sản', ex: 'Angkor Wat is a heritage site.', coll: 'World Heritage Site' },
      { w: 'currency', ipa: '/ˈkʌrənsi/', pos: 'n', vi: 'tiền tệ', ex: 'Exchange currency before traveling.', coll: 'foreign currency, local currency' },
      { w: 'visa', ipa: '/ˈviːzə/', pos: 'n', vi: 'thị thực', ex: 'You need a visa to enter the country.', coll: 'apply for a visa, tourist visa' },
      { w: 'roundabout route', ipa: '/ˈraʊndəbaʊt ruːt/', pos: 'n', vi: 'đường đi vòng', ex: 'We took a roundabout route through the mountains.', coll: 'take a roundabout route' },
      { w: 'guided tour', ipa: '/ˈɡaɪdɪd tʊə/', pos: 'n', vi: 'tour có hướng dẫn', ex: 'We joined a guided tour of the museum.', coll: 'go on a guided tour' },
      { w: 'tourist trap', ipa: '/ˈtʊərɪst træp/', pos: 'n', vi: 'điểm bẫy du khách', ex: 'This restaurant is a tourist trap.', coll: 'avoid tourist traps' },
      { w: 'remote', ipa: '/rɪˈməʊt/', pos: 'adj', vi: 'xa xôi', ex: 'They live in a remote village.', coll: 'remote area/location' },
      { w: 'commute', ipa: '/kəˈmjuːt/', pos: 'v/n', vi: 'đi lại', ex: 'I commute by metro.', coll: 'daily commute' },
      { w: 'all-inclusive', ipa: '/ˌɔːl ɪnˈkluːsɪv/', pos: 'adj', vi: 'trọn gói', ex: 'They booked an all-inclusive resort.', coll: 'all-inclusive package' },
      { w: 'embark on', ipa: '/ɪmˈbɑːk ɒn/', pos: 'phrase', vi: 'bắt đầu (chuyến đi)', ex: 'We embarked on a journey across Asia.', coll: 'embark on a journey' },
      { w: 'overseas', ipa: '/ˌəʊvəˈsiːz/', pos: 'adj', vi: 'ở nước ngoài', ex: 'She has overseas business interests.', coll: 'overseas travel, study overseas' },
      { w: 'budget', ipa: '/ˈbʌdʒɪt/', pos: 'n/adj', vi: 'ngân sách/giá rẻ', ex: 'I traveled on a tight budget.', coll: 'tight budget, budget airline' }
    ]
  },

  // ==================== MEDIA ====================
  'media': {
    title: 'Media',
    titleVi: 'Truyền thông',
    icon: '📰',
    color: 'lavender',
    words: [
      { w: 'broadcast', ipa: '/ˈbrɔːdkɑːst/', pos: 'v/n', vi: 'phát sóng', ex: 'The news is broadcast live every evening.', coll: 'live broadcast, broadcast news' },
      { w: 'censorship', ipa: '/ˈsensəʃɪp/', pos: 'n', vi: 'sự kiểm duyệt', ex: 'Press censorship limits free speech.', coll: 'press censorship, government censorship' },
      { w: 'biased', ipa: '/ˈbaɪəst/', pos: 'adj', vi: 'thiên vị', ex: 'The article appears to be biased.', coll: 'biased reporting/coverage' },
      { w: 'mainstream media', ipa: '/ˈmeɪnstriːm ˈmiːdiə/', pos: 'n', vi: 'truyền thông chính thống', ex: 'Mainstream media shapes public opinion.', coll: 'mainstream media outlets' },
      { w: 'tabloid', ipa: '/ˈtæblɔɪd/', pos: 'n', vi: 'báo lá cải', ex: 'Tabloids focus on celebrity gossip.', coll: 'tabloid newspaper, tabloid journalism' },
      { w: 'editorial', ipa: '/ˌedɪˈtɔːriəl/', pos: 'n/adj', vi: 'bài xã luận', ex: 'The editorial criticized the policy.', coll: 'editorial board, editorial decision' },
      { w: 'sensationalism', ipa: '/senˈseɪʃənəlɪzəm/', pos: 'n', vi: 'giật gân', ex: 'Sensationalism distorts reality.', coll: 'media sensationalism' },
      { w: 'coverage', ipa: '/ˈkʌvərɪdʒ/', pos: 'n', vi: 'sự đưa tin', ex: 'The event received extensive coverage.', coll: 'extensive coverage, news coverage' },
      { w: 'headline', ipa: '/ˈhedlaɪn/', pos: 'n', vi: 'tiêu đề', ex: 'The headline grabbed my attention.', coll: 'make headlines, front-page headline' },
      { w: 'subscribe', ipa: '/səbˈskraɪb/', pos: 'v', vi: 'đăng ký', ex: 'I subscribe to several newspapers.', coll: 'subscribe to a magazine' },
      { w: 'press freedom', ipa: '/pres ˈfriːdəm/', pos: 'n', vi: 'tự do báo chí', ex: 'Press freedom is essential to democracy.', coll: 'defend press freedom' },
      { w: 'propaganda', ipa: '/ˌprɒpəˈɡændə/', pos: 'n', vi: 'tuyên truyền', ex: 'The regime used propaganda extensively.', coll: 'spread propaganda, political propaganda' },
      { w: 'commentator', ipa: '/ˈkɒmənteɪtə/', pos: 'n', vi: 'bình luận viên', ex: 'Political commentators analyzed the debate.', coll: 'political/sports commentator' },
      { w: 'viral', ipa: '/ˈvaɪrəl/', pos: 'adj', vi: 'lan truyền nhanh', ex: 'The video went viral overnight.', coll: 'go viral, viral video' },
      { w: 'influencer', ipa: '/ˈɪnfluənsə/', pos: 'n', vi: 'người có sức ảnh hưởng', ex: 'Influencers shape consumer behavior.', coll: 'social media influencer' },
      { w: 'audience', ipa: '/ˈɔːdiəns/', pos: 'n', vi: 'khán giả', ex: 'The show reaches a wide audience.', coll: 'target audience, mass audience' },
      { w: 'cover up', ipa: '/ˈkʌvər ʌp/', pos: 'phrasal v', vi: 'che giấu', ex: 'The scandal was covered up for years.', coll: 'cover up the truth' },
      { w: 'integrity', ipa: '/ɪnˈteɡrəti/', pos: 'n', vi: 'tính chính trực', ex: 'Journalistic integrity is vital.', coll: 'journalistic integrity' },
      { w: 'fake news', ipa: '/ˌfeɪk ˈnjuːz/', pos: 'n', vi: 'tin giả', ex: 'Fake news spreads rapidly online.', coll: 'spread fake news, combat fake news' },
      { w: 'documentary', ipa: '/ˌdɒkjuˈmentəri/', pos: 'n', vi: 'phim tài liệu', ex: 'The documentary exposed corruption.', coll: 'watch a documentary, make a documentary' },
      { w: 'celebrity', ipa: '/səˈlebrəti/', pos: 'n', vi: 'người nổi tiếng', ex: 'Celebrities have huge influence.', coll: 'celebrity culture, A-list celebrity' },
      { w: 'paparazzi', ipa: '/ˌpæpəˈrætsi/', pos: 'n', vi: 'thợ săn ảnh', ex: 'Paparazzi follow celebrities everywhere.', coll: 'hounded by paparazzi' },
      { w: 'subscription', ipa: '/səbˈskrɪpʃn/', pos: 'n', vi: 'sự đăng ký', ex: 'My Netflix subscription expired.', coll: 'monthly subscription, cancel subscription' },
      { w: 'streaming', ipa: '/ˈstriːmɪŋ/', pos: 'n', vi: 'phát trực tuyến', ex: 'Streaming services dominate entertainment.', coll: 'streaming service/platform' },
      { w: 'controversial', ipa: '/ˌkɒntrəˈvɜːʃl/', pos: 'adj', vi: 'gây tranh cãi', ex: 'The article sparked controversial debate.', coll: 'controversial issue/topic' },
      { w: 'pundit', ipa: '/ˈpʌndɪt/', pos: 'n', vi: 'chuyên gia bình luận', ex: 'Political pundits made predictions.', coll: 'political pundit' },
      { w: 'newsworthy', ipa: '/ˈnjuːzwɜːði/', pos: 'adj', vi: 'đáng đưa tin', ex: 'Not every event is newsworthy.', coll: 'newsworthy event/story' },
      { w: 'exposé', ipa: '/ɪkˈspəʊzeɪ/', pos: 'n', vi: 'phơi bày', ex: 'The exposé revealed corporate fraud.', coll: 'shocking exposé' },
      { w: 'rating', ipa: '/ˈreɪtɪŋ/', pos: 'n', vi: 'xếp hạng', ex: 'The show has high ratings.', coll: 'TV ratings, ratings drop' },
      { w: 'reliable source', ipa: '/rɪˈlaɪəbl sɔːs/', pos: 'n', vi: 'nguồn tin đáng tin cậy', ex: 'Always check from reliable sources.', coll: 'cite reliable sources' }
    ]
  },

  // ==================== CRIME ====================
  'crime': {
    title: 'Crime & Law',
    titleVi: 'Tội phạm & Luật',
    icon: '⚖️',
    color: 'coral',
    words: [
      { w: 'offence', ipa: '/əˈfens/', pos: 'n', vi: 'tội phạm', ex: 'Shoplifting is a minor offence.', coll: 'commit an offence, criminal offence' },
      { w: 'convict', ipa: '/kənˈvɪkt/', pos: 'v', vi: 'kết tội', ex: 'He was convicted of theft.', coll: 'convict of a crime' },
      { w: 'sentence', ipa: '/ˈsentəns/', pos: 'n/v', vi: 'án phạt/tuyên án', ex: 'She received a five-year prison sentence.', coll: 'serve a sentence, life sentence' },
      { w: 'rehabilitation', ipa: '/ˌriːəˌbɪlɪˈteɪʃn/', pos: 'n', vi: 'phục hồi', ex: 'Rehabilitation reduces reoffending.', coll: 'prisoner rehabilitation' },
      { w: 'deterrent', ipa: '/dɪˈterənt/', pos: 'n', vi: 'sự răn đe', ex: 'Long sentences act as a deterrent.', coll: 'effective deterrent' },
      { w: 'parole', ipa: '/pəˈrəʊl/', pos: 'n', vi: 'án treo, tạm tha', ex: 'He was released on parole.', coll: 'on parole, parole hearing' },
      { w: 'evidence', ipa: '/ˈevɪdəns/', pos: 'n', vi: 'bằng chứng', ex: 'There was insufficient evidence.', coll: 'gather evidence, conclusive evidence' },
      { w: 'witness', ipa: '/ˈwɪtnəs/', pos: 'n/v', vi: 'nhân chứng', ex: 'Several witnesses testified.', coll: 'eye witness, key witness' },
      { w: 'verdict', ipa: '/ˈvɜːdɪkt/', pos: 'n', vi: 'phán quyết', ex: 'The jury delivered a guilty verdict.', coll: 'reach a verdict, guilty verdict' },
      { w: 'prosecution', ipa: '/ˌprɒsɪˈkjuːʃn/', pos: 'n', vi: 'việc truy tố', ex: 'The prosecution called its first witness.', coll: 'face prosecution' },
      { w: 'defendant', ipa: '/dɪˈfendənt/', pos: 'n', vi: 'bị cáo', ex: 'The defendant pleaded not guilty.', coll: 'the defendant claimed' },
      { w: 'fraud', ipa: '/frɔːd/', pos: 'n', vi: 'gian lận', ex: 'He was charged with fraud.', coll: 'commit fraud, tax fraud' },
      { w: 'theft', ipa: '/θeft/', pos: 'n', vi: 'trộm cắp', ex: 'Petty theft is increasing.', coll: 'commit theft, petty theft' },
      { w: 'vandalism', ipa: '/ˈvændəlɪzəm/', pos: 'n', vi: 'phá hoại tài sản', ex: 'Vandalism damages the community.', coll: 'act of vandalism' },
      { w: 'corruption', ipa: '/kəˈrʌpʃn/', pos: 'n', vi: 'tham nhũng', ex: 'Corruption undermines democracy.', coll: 'fight corruption, political corruption' },
      { w: 'capital punishment', ipa: '/ˈkæpɪtl ˈpʌnɪʃmənt/', pos: 'n', vi: 'tử hình', ex: 'Many countries have abolished capital punishment.', coll: 'abolish capital punishment' },
      { w: 'criminal', ipa: '/ˈkrɪmɪnl/', pos: 'n/adj', vi: 'tội phạm/thuộc về tội phạm', ex: 'Repeat criminals face harsher penalties.', coll: 'criminal record, hardened criminal' },
      { w: 'commit', ipa: '/kəˈmɪt/', pos: 'v', vi: 'phạm tội', ex: 'They committed a serious crime.', coll: 'commit a crime/an offence' },
      { w: 'illegal', ipa: '/ɪˈliːɡl/', pos: 'adj', vi: 'bất hợp pháp', ex: 'Drug trafficking is illegal.', coll: 'illegal activity, illegal drug' },
      { w: 'lenient', ipa: '/ˈliːniənt/', pos: 'adj', vi: 'khoan dung', ex: 'The judge was too lenient.', coll: 'lenient sentence, lenient approach' },
      { w: 'enforce', ipa: '/ɪnˈfɔːs/', pos: 'v', vi: 'thực thi', ex: 'Police enforce the law.', coll: 'enforce the law, strictly enforce' },
      { w: 'jurisdiction', ipa: '/ˌdʒʊərɪsˈdɪkʃn/', pos: 'n', vi: 'quyền tài phán', ex: 'The court has jurisdiction over this case.', coll: 'fall under jurisdiction' },
      { w: 'cybercrime', ipa: '/ˈsaɪbəkraɪm/', pos: 'n', vi: 'tội phạm mạng', ex: 'Cybercrime is rising globally.', coll: 'combat cybercrime' },
      { w: 'recidivism', ipa: '/rɪˈsɪdɪvɪzəm/', pos: 'n', vi: 'tái phạm', ex: 'High recidivism rates concern officials.', coll: 'reduce recidivism' },
      { w: 'imprisonment', ipa: '/ɪmˈprɪznmənt/', pos: 'n', vi: 'tù giam', ex: 'He faces life imprisonment.', coll: 'life imprisonment' },
      { w: 'minor offence', ipa: '/ˈmaɪnər əˈfens/', pos: 'n', vi: 'tội nhẹ', ex: 'Minor offences should not result in jail.', coll: 'commit minor offences' },
      { w: 'plea', ipa: '/pliː/', pos: 'n', vi: 'lời nhận tội', ex: 'She entered a guilty plea.', coll: 'guilty plea, enter a plea' },
      { w: 'crackdown', ipa: '/ˈkrækdaʊn/', pos: 'n', vi: 'sự trấn áp', ex: 'There was a crackdown on smuggling.', coll: 'crackdown on, launch a crackdown' },
      { w: 'embezzle', ipa: '/ɪmˈbezl/', pos: 'v', vi: 'biển thủ', ex: 'The CEO embezzled millions.', coll: 'embezzle funds/money' },
      { w: 'detention', ipa: '/dɪˈtenʃn/', pos: 'n', vi: 'sự giam giữ', ex: 'He was held in detention.', coll: 'in detention, detention centre' }
    ]
  },

  // ==================== FAMILY & LIFESTYLE ====================
  'family': {
    title: 'Family & Lifestyle',
    titleVi: 'Gia đình & Lối sống',
    icon: '👨‍👩‍👧',
    color: 'tangerine',
    words: [
      { w: 'nuclear family', ipa: '/ˈnjuːkliə ˈfæməli/', pos: 'n', vi: 'gia đình hạt nhân', ex: 'The nuclear family is the most common today.', coll: 'modern nuclear family' },
      { w: 'extended family', ipa: '/ɪkˈstendɪd ˈfæməli/', pos: 'n', vi: 'gia đình mở rộng', ex: 'Extended families live together in many cultures.', coll: 'large extended family' },
      { w: 'sibling', ipa: '/ˈsɪblɪŋ/', pos: 'n', vi: 'anh/chị/em ruột', ex: 'She has three siblings.', coll: 'sibling rivalry, older sibling' },
      { w: 'parenting', ipa: '/ˈpeərəntɪŋ/', pos: 'n', vi: 'việc nuôi dạy con', ex: 'Parenting requires patience.', coll: 'parenting style, single parenting' },
      { w: 'upbringing', ipa: '/ˈʌpbrɪŋɪŋ/', pos: 'n', vi: 'cách nuôi dạy', ex: 'His strict upbringing shaped his values.', coll: 'strict upbringing' },
      { w: 'bond', ipa: '/bɒnd/', pos: 'n/v', vi: 'mối liên kết', ex: 'They share a strong bond.', coll: 'strong bond, family bond' },
      { w: 'in-laws', ipa: '/ˈɪn lɔːz/', pos: 'n', vi: 'gia đình bên vợ/chồng', ex: 'I visit my in-laws on weekends.', coll: 'live with in-laws' },
      { w: 'breadwinner', ipa: '/ˈbredwɪnə/', pos: 'n', vi: 'trụ cột gia đình', ex: 'He is the family\'s main breadwinner.', coll: 'main/sole breadwinner' },
      { w: 'household chores', ipa: '/ˈhaʊshəʊld tʃɔːz/', pos: 'n', vi: 'việc nhà', ex: 'They share the household chores.', coll: 'do household chores' },
      { w: 'spouse', ipa: '/spaʊs/', pos: 'n', vi: 'vợ/chồng', ex: 'Choose your spouse carefully.', coll: 'former/future spouse' },
      { w: 'cohabit', ipa: '/kəʊˈhæbɪt/', pos: 'v', vi: 'sống chung không kết hôn', ex: 'Many couples cohabit before marriage.', coll: 'cohabit with a partner' },
      { w: 'divorce', ipa: '/dɪˈvɔːs/', pos: 'n/v', vi: 'ly hôn', ex: 'Divorce rates have increased.', coll: 'get a divorce, file for divorce' },
      { w: 'single parent', ipa: '/ˈsɪŋɡl ˈpeərənt/', pos: 'n', vi: 'cha/mẹ đơn thân', ex: 'Single parents face many challenges.', coll: 'single-parent family' },
      { w: 'sibling rivalry', ipa: '/ˈsɪblɪŋ ˈraɪvlri/', pos: 'n', vi: 'mâu thuẫn anh chị em', ex: 'Sibling rivalry is common in childhood.', coll: 'intense sibling rivalry' },
      { w: 'discipline', ipa: '/ˈdɪsəplɪn/', pos: 'n/v', vi: 'kỷ luật', ex: 'Children need discipline.', coll: 'strict discipline, self-discipline' },
      { w: 'role model', ipa: '/ˈrəʊl mɒdl/', pos: 'n', vi: 'hình mẫu', ex: 'Parents should be positive role models.', coll: 'positive role model' },
      { w: 'generation gap', ipa: '/ˌdʒenəˈreɪʃn ɡæp/', pos: 'n', vi: 'khoảng cách thế hệ', ex: 'A generation gap exists in our family.', coll: 'bridge the generation gap' },
      { w: 'household', ipa: '/ˈhaʊshəʊld/', pos: 'n', vi: 'hộ gia đình', ex: 'Most households now have internet.', coll: 'low-income household' },
      { w: 'caregiver', ipa: '/ˈkeəɡɪvə/', pos: 'n', vi: 'người chăm sóc', ex: 'Primary caregivers are usually mothers.', coll: 'primary caregiver' },
      { w: 'pamper', ipa: '/ˈpæmpə/', pos: 'v', vi: 'nuông chiều', ex: 'They pamper their only child.', coll: 'pamper a child' },
      { w: 'discipline', ipa: '/ˈdɪsəplɪn/', pos: 'v', vi: 'kỷ luật', ex: 'Don\'t discipline children harshly.', coll: 'discipline a child' },
      { w: 'home-schooled', ipa: '/ˌhəʊm ˈskuːld/', pos: 'adj', vi: 'học tại nhà', ex: 'Their children are home-schooled.', coll: 'home-schooled child' },
      { w: 'pursue a career', ipa: '/pəˈsjuː ə kəˈrɪə/', pos: 'phrase', vi: 'theo đuổi sự nghiệp', ex: 'Many women pursue a career after children.', coll: 'pursue a successful career' },
      { w: 'work-life balance', ipa: '/ˈwɜːk laɪf ˈbæləns/', pos: 'n', vi: 'cân bằng công việc-cuộc sống', ex: 'Maintain a healthy work-life balance.', coll: 'achieve work-life balance' },
      { w: 'family-oriented', ipa: '/ˈfæməli ˈɔːrientɪd/', pos: 'adj', vi: 'lấy gia đình làm trung tâm', ex: 'Asian cultures are family-oriented.', coll: 'family-oriented society' },
      { w: 'maternity leave', ipa: '/məˈtɜːnəti liːv/', pos: 'n', vi: 'nghỉ thai sản', ex: 'She is on maternity leave.', coll: 'take maternity leave' },
      { w: 'paternity leave', ipa: '/pəˈtɜːnəti liːv/', pos: 'n', vi: 'nghỉ chăm vợ sinh', ex: 'Many countries now offer paternity leave.', coll: 'extended paternity leave' },
      { w: 'tradition', ipa: '/trəˈdɪʃn/', pos: 'n', vi: 'truyền thống', ex: 'Family traditions strengthen bonds.', coll: 'family tradition, cherish tradition' },
      { w: 'overprotective', ipa: '/ˌəʊvəprəˈtektɪv/', pos: 'adj', vi: 'bảo bọc quá mức', ex: 'Overprotective parents harm independence.', coll: 'overprotective parent' },
      { w: 'inherit', ipa: '/ɪnˈherɪt/', pos: 'v', vi: 'thừa kế', ex: 'She inherited her grandmother\'s house.', coll: 'inherit property/wealth' }
    ]
  }
};

const VOCAB_TOPICS = Object.keys(VOCAB_DATA);
